### ISSUE TITLE
Issue 1: fire a missile programmatically

### ISSUE THREAD

**Issue by annacal** [wilkinsmt1/CPTS-323-SAD-Project#1]
I want fire a missile for the project.

**Comment by brianlamarche** [comment]
You should add a "user story" label to this as well.  And all subsequent user stories.  

Your user story should also be in the form

As a <user> I want <feature> because <reason>

Right now the user is you, but has no definition of who you are.  The feature is "fire a missile".  No reason is evident.   I would possibly include "fire a missile programmatically"

**Comment by wilkinsmt1** [comment]
Missile launcher/SADCL program fires missiles, this was achieved by controlling the missile launcher by adapting code from MissileLauncher.cs.

So this one is closed!
